"""Catálogo mecânico/canônico de NPCs do Sea's Paradise.

Os pontos abaixo são BALANCEAMENTO DO RP (0..50.000), não números oficiais de One Piece.
`publico` alimenta !status/!npcstatus; `combate` é contexto interno do Narrador.
A fase padrão é a fase coerente com a localização inicial do NPC no projeto.
"""

NPC_PROFILES = {
    "makino": dict(nome="Makino", titulo="Dona do bar", classificacao="Civil", raca="Humana", faccao="Civil", forca=35, resistencia=45, velocidade=40, akuma="Nenhuma", haki="Não conhecido", estilo="Civil", arma="Nenhuma", publico="Civil de Vila Foosha; não é conhecida como combatente.", combate="Evita combate, protege civis e procura ajuda. Não inventar técnicas de luta."),
    "woop slap": dict(nome="Woop Slap", titulo="Prefeito", classificacao="Civil", raca="Humano", faccao="Civil", forca=45, resistencia=55, velocidade=40, akuma="Nenhuma", haki="Não conhecido", estilo="Civil", arma="Nenhuma", publico="Prefeito de Vila Foosha.", combate="Não é combatente relevante; age como autoridade civil."),
    "higuma": dict(nome="Higuma", titulo="Líder dos Bandidos da Montanha", classificacao="Bandido", raca="Humano", faccao="Bandido", forca=260, resistencia=220, velocidade=240, akuma="Nenhuma", haki="Nenhum conhecido", estilo="Briga armada", arma="Espada", publico="Bandido da montanha e líder de um pequeno grupo.", combate="Luta sujo, usa espada, números e intimidação; foge se a situação virar contra ele."),
    "alvida": dict(nome="Alvida", titulo="Capitã Pirata", classificacao="Pirata do East Blue", raca="Humana", faccao="Pirata", forca=520, resistencia=560, velocidade=300, akuma="Nenhuma nesta fase", haki="Nenhum", estilo="Força bruta", arma="Clava de ferro", publico="Capitã pirata conhecida pela força bruta e pela grande clava.", combate="Nesta fase inicial, usa principalmente a enorme clava e força física. Não dar Sube Sube no Mi antes da fase correspondente."),
    "koby": dict(nome="Koby", titulo="Recruta da Marinha", classificacao="Recruta", raca="Humano", faccao="Marinha", forca=90, resistencia=90, velocidade=100, akuma="Nenhuma", haki="Não nesta fase", estilo="Treinamento básico", arma="Padrão da Marinha", publico="Jovem recruta em início de treinamento.", combate="Fase inicial: inexperiente, corajoso quando necessário, sem capacidades futuras de Rokushiki/Haki."),
    "helmeppo": dict(nome="Helmeppo", titulo="Recruta da Marinha", classificacao="Recruta", raca="Humano", faccao="Marinha", forca=80, resistencia=85, velocidade=90, akuma="Nenhuma", haki="Não nesta fase", estilo="Treinamento básico", arma="Armas da Marinha", publico="Recruta ainda em formação.", combate="Fase inicial; não usar capacidades futuras."),
    "morgan": dict(nome="Axe-Hand Morgan", titulo="Capitão da Marinha", classificacao="Oficial do East Blue", raca="Humano", faccao="Marinha", forca=850, resistencia=780, velocidade=520, akuma="Nenhuma", haki="Nenhum", estilo="Força bruta", arma="Machado no braço direito", publico="Oficial da Marinha conhecido pelo enorme machado incorporado ao braço.", combate="Usa o machado protético em golpes pesados e autoridade sobre soldados; agressivo e autoritário."),
    "roronoa zoro": dict(nome="Roronoa Zoro", titulo="Caçador de Piratas", classificacao="Espadachim de elite do East Blue", raca="Humano", faccao="Independente", forca=2400, resistencia=2700, velocidade=2200, akuma="Nenhuma", haki="Não disponível conscientemente nesta fase", estilo="Santoryu / Nitoryu / Ittoryu", arma="Três espadas", publico="Famoso caçador de piratas e espadachim de três espadas.", combate="Usa Santoryu, Nitoryu e Ittoryu compatíveis com a fase. Resistência e força excepcionais. Não liberar Haki consciente ou técnicas de arcos futuros."),
    "buggy": dict(nome="Buggy", titulo="Capitão dos Piratas Buggy", classificacao="Capitão Pirata", raca="Humano", faccao="Pirata", forca=900, resistencia=1150, velocidade=850, akuma="Bara Bara no Mi", haki="Nenhum conhecido nesta fase", estilo="Combate ardiloso", arma="Facas e Buggy Balls", publico="Capitão pirata usuário da Bara Bara no Mi; seu corpo pode se separar em partes.", combate="Usa Bara Bara no Mi ativamente para separar corpo, evitar cortes e atacar de ângulos incomuns; usa facas, truques e Buggy Balls. Cortes comuns não funcionam como contra humano normal."),
    "cabaji": dict(nome="Cabaji", titulo="Chefe de Estado-Maior", classificacao="Oficial Pirata", raca="Humano", faccao="Pirata", forca=650, resistencia=620, velocidade=760, akuma="Nenhuma", haki="Nenhum", estilo="Acrobacia e espada", arma="Espada / monociclo", publico="Espadachim acrobático dos Piratas Buggy.", combate="Combina espada, monociclo, acrobacias e truques; luta de forma desleal quando útil."),
    "mohji": dict(nome="Mohji", titulo="Domador de Feras", classificacao="Oficial Pirata", raca="Humano", faccao="Pirata", forca=580, resistencia=600, velocidade=470, akuma="Nenhuma", haki="Nenhum", estilo="Domador", arma="Richie", publico="Domador de feras dos Piratas Buggy, normalmente acompanhado de Richie.", combate="Usa Richie como principal força ofensiva; não o transformar em espadachim genérico."),
    "richie": dict(nome="Richie", titulo="Leão de Mohji", classificacao="Fera", raca="Leão", faccao="Pirata", forca=700, resistencia=680, velocidade=620, akuma="Nenhuma", haki="Nenhum", estilo="Fera", arma="Garras e presas", publico="Grande leão treinado por Mohji.", combate="Ataca com massa corporal, garras, mordidas e investidas; comportamento animal treinado."),
    "kuro": dict(nome="Kuro", titulo="Capitão Kuro", classificacao="Capitão Pirata", raca="Humano", faccao="Pirata", forca=1250, resistencia=1050, velocidade=2100, akuma="Nenhuma", haki="Nenhum", estilo="Nukite / Shakushi", arma="Garras longas", publico="Pirata extremamente veloz que luta com longas lâminas presas às mãos.", combate="Velocidade é sua maior vantagem. Usa Nuki Ashi/Shakushi e garras; Shakushi é veloz mas pouco controlado. É calculista fora do frenesi."),
    "kaya": dict(nome="Kaya", titulo="Herdeira de Vila Syrup", classificacao="Civil", raca="Humana", faccao="Civil", forca=20, resistencia=25, velocidade=30, akuma="Nenhuma", haki="Nenhum", estilo="Civil", arma="Nenhuma", publico="Jovem civil de saúde frágil.", combate="Não é combatente; prioriza fugir, pedir ajuda e sobreviver."),
    "usopp": dict(nome="Usopp", titulo="Atirador", classificacao="Combatente iniciante", raca="Humano", faccao="Civil", forca=180, resistencia=300, velocidade=280, akuma="Nenhuma", haki="Não nesta fase", estilo="Atirador / improvisação", arma="Estilingue e munições artesanais", publico="Atirador inventivo de Vila Syrup.", combate="Usa distância, blefes, pólvora, munições improvisadas e terreno. Não usar Kabuto, Pop Greens ou Haki de fases futuras."),
    "zeff": dict(nome="Zeff", titulo="Zeff Perna Vermelha", classificacao="Veterano", raca="Humano", faccao="Civil", forca=3200, resistencia=3500, velocidade=2900, akuma="Nenhuma", haki="Não confirmado para uso neste RP", estilo="Chutes", arma="Pernas", publico="Ex-pirata e chefe do Baratie; famoso pelo combate com chutes.", combate="Veterano perigosíssimo do East Blue, usa exclusivamente chutes e experiência. Não o tratar como cozinheiro indefeso."),
    "sanji": dict(nome="Sanji", titulo="Cozinheiro do Baratie", classificacao="Combatente de elite do East Blue", raca="Humano", faccao="Civil", forca=2200, resistencia=2300, velocidade=2600, akuma="Nenhuma", haki="Não disponível nesta fase", estilo="Black Leg Style", arma="Pernas", publico="Cozinheiro e lutador especializado exclusivamente em chutes.", combate="Usa Black Leg Style e protege as mãos por serem ferramentas de cozinheiro. Não usar Diable Jambe, Haki ou capacidades genéticas futuras nesta fase."),
    "don krieg": dict(nome="Don Krieg", titulo="Almirante da Frota Krieg", classificacao="Capitão Pirata do East Blue", raca="Humano", faccao="Pirata", forca=2500, resistencia=3000, velocidade=1450, akuma="Nenhuma", haki="Nenhum", estilo="Arsenal e força bruta", arma="Armadura, lança, armas ocultas e explosivos", publico="Pirata fortemente armado, conhecido por armadura e enorme arsenal.", combate="Usa armadura, lança MH5/gás venenoso quando coerente, projéteis, explosivos e armas ocultas. Trapaceiro e pragmático; não lutar como brutamontes desarmado."),
    "gin": dict(nome="Gin", titulo="Gin, o Demônio", classificacao="Oficial Pirata", raca="Humano", faccao="Pirata", forca=1900, resistencia=1800, velocidade=1850, akuma="Nenhuma", haki="Nenhum", estilo="Tonfas de ferro", arma="Tonfas com esferas metálicas", publico="Principal combatente da Frota Krieg depois do capitão.", combate="Combate rápido e brutal com tonfas pesadas; lealdade e conflito moral podem afetar decisões."),
    "dracule mihawk": dict(nome="Dracule Mihawk", titulo="Olhos de Falcão", classificacao="Espadachim do topo mundial", raca="Humano", faccao="Pirata", forca=49000, resistencia=48500, velocidade=49500, akuma="Nenhuma", haki="Armamento e Observação de altíssimo nível", estilo="Espadachim supremo", arma="Yoru", publico="Reconhecido como o maior espadachim do mundo; enfrentar diretamente é risco extremo.", combate="Usa precisão, leitura, velocidade e poder de corte absurdos, Yoru e Haki canônico. Pode derrotar iniciantes com esforço mínimo; não precisa 'trocar golpes' para dar chance dramática."),
    "arlong": dict(nome="Arlong", titulo="Capitão dos Piratas Arlong", classificacao="Homem-Peixe de elite do East Blue", raca="Homem-Peixe tubarão-serra", faccao="Pirata", forca=4200, resistencia=4500, velocidade=3300, akuma="Nenhuma", haki="Nenhum", estilo="Karate Homem-Peixe / força racial", arma="Kiribachi / dentes", publico="Capitão homem-peixe extremamente forte; torna-se ainda mais perigoso na água.", combate="Explora força racial, dentes que regeneram, nariz serrilhado, Kiribachi e vantagem aquática. Não lutar como humano comum."),
    "hatchan": dict(nome="Hatchan", titulo="Oficial dos Piratas Arlong", classificacao="Homem-Peixe combatente", raca="Homem-Peixe polvo", faccao="Pirata", forca=2600, resistencia=2800, velocidade=2200, akuma="Nenhuma", haki="Nenhum", estilo="Rokutoryu", arma="Seis espadas", publico="Homem-peixe polvo que luta empunhando seis espadas.", combate="Usa seis braços e Rokutoryu, força homem-peixe e mobilidade aquática."),
    "kuroobi": dict(nome="Kuroobi", titulo="Oficial dos Piratas Arlong", classificacao="Homem-Peixe combatente", raca="Homem-Peixe arraia", faccao="Pirata", forca=2800, resistencia=3000, velocidade=2450, akuma="Nenhuma", haki="Nenhum", estilo="Karate Homem-Peixe", arma="Corpo", publico="Especialista em Karate Homem-Peixe.", combate="Usa Karate Homem-Peixe e fica muito mais perigoso debaixo d'água."),
    "chew": dict(nome="Chew", titulo="Oficial dos Piratas Arlong", classificacao="Homem-Peixe combatente", raca="Homem-Peixe", faccao="Pirata", forca=2100, resistencia=2300, velocidade=2100, akuma="Nenhuma", haki="Nenhum", estilo="Combate aquático", arma="Jatos d'água", publico="Homem-peixe capaz de usar água como projétil.", combate="Cospe jatos/projéteis de água com força e usa capacidades raciais; prefere alcance."),
    "smoker": dict(nome="Smoker", titulo="Capitão da Marinha", classificacao="Oficial de elite de Loguetown", raca="Humano", faccao="Marinha", forca=7000, resistencia=7600, velocidade=7200, akuma="Moku Moku no Mi", haki="Não usar Haki explicitamente nesta fase inicial", estilo="Logia / combate com jitte", arma="Jitte com ponta de Kairouseki", publico="Oficial da Marinha usuário da Moku Moku no Mi e portador de jitte com Kairouseki.", combate="Usa fumaça para mobilidade, captura, intangibilidade Logia e contenção; combina com jitte de Kairouseki. Sem Haki explícito de fases posteriores."),
    "tashigi": dict(nome="Tashigi", titulo="Sargento-Mor da Marinha", classificacao="Espadachim da Marinha", raca="Humana", faccao="Marinha", forca=1400, resistencia=1500, velocidade=1700, akuma="Nenhuma", haki="Não nesta fase", estilo="Espadachim", arma="Shigure", publico="Espadachim da Marinha obcecada por recuperar espadas famosas de criminosos.", combate="Usa esgrima disciplinada e conhecimento de espadas; não usar Haki de fases posteriores."),
    "monkey d. dragon": dict(nome="Monkey D. Dragon", titulo="Líder do Exército Revolucionário", classificacao="Ameaça mundial", raca="Humano", faccao="Revolucionário", forca=48000, resistencia=48000, velocidade=48500, akuma="Não revelada/confirmada", haki="Capacidades exatas não expostas publicamente", estilo="Desconhecido", arma="Desconhecida", publico="Líder do Exército Revolucionário e um dos homens mais procurados do mundo. Muitas capacidades permanecem desconhecidas.", combate="Não inventar Akuma no Mi, técnicas ou Haki específico não confirmado. Ainda assim, tratá-lo como figura de ameaça máxima e não como combatente genérico."),
    "kizaru": dict(nome="Kizaru (Borsalino)", titulo="Almirante da Marinha", classificacao="Almirante", raca="Humano", faccao="Marinha", forca=45000, resistencia=45500, velocidade=50000, akuma="Pika Pika no Mi", haki="Armamento e Observação", estilo="Logia / chutes / espada de luz", arma="Luz criada pela fruta", publico="Almirante usuário da Pika Pika no Mi, capaz de lutar e se mover por aplicações de luz.", combate="Usa Pika Pika no Mi ativamente: deslocamentos luminosos, lasers, chutes e espada de luz; Haki canônico. Contra iniciantes pode neutralizar antes de reação plausível."),
    "akainu": dict(nome="Akainu (Sakazuki)", titulo="Almirante da Marinha", classificacao="Almirante", raca="Humano", faccao="Marinha", forca=49000, resistencia=50000, velocidade=45500, akuma="Magu Magu no Mi", haki="Armamento e Observação", estilo="Logia ofensiva", arma="Magma", publico="Almirante usuário da Magu Magu no Mi, com poder ofensivo extremo.", combate="Usa magma de modo devastador e força letal quando julga necessário; Haki canônico. Personalidade severa e doutrina de Justiça Absoluta."),
    "aokiji": dict(nome="Aokiji (Kuzan)", titulo="Almirante da Marinha", classificacao="Almirante", raca="Humano", faccao="Marinha", forca=46500, resistencia=48000, velocidade=46000, akuma="Hie Hie no Mi", haki="Armamento e Observação", estilo="Logia / congelamento", arma="Gelo", publico="Almirante usuário da Hie Hie no Mi, capaz de congelamento em escala massiva.", combate="Usa gelo para congelar alvos, terreno e mar, criar armas e controlar área; Haki canônico. Temperamento relaxado não significa passividade em ameaça real."),
    "sengoku": dict(nome="Sengoku", titulo="Almirante de Frota", classificacao="Alto Comando", raca="Humano", faccao="Marinha", forca=49500, resistencia=50000, velocidade=47000, akuma="Hito Hito no Mi, Modelo: Daibutsu", haki="Haki de altíssimo nível; Haoshoku confirmado", estilo="Zoan Mítica / ondas de choque", arma="Corpo / forma Daibutsu", publico="Almirante de Frota e veterano lendário da Marinha.", combate="Pode usar forma Daibutsu, enorme força e ondas de choque; estrategista de alto nível e usuário de Haki. Não o reduzir a comandante administrativo."),
    "garp": dict(nome="Monkey D. Garp", titulo="Herói da Marinha", classificacao="Lenda da Marinha", raca="Humano", faccao="Marinha", forca=50000, resistencia=50000, velocidade=48500, akuma="Nenhuma", haki="Armamento, Observação e Haoshoku", estilo="Combate físico / punhos", arma="Punhos", publico="Herói lendário da Marinha, famoso por força física e Haki extraordinários.", combate="Combate com força física e Haki monstruosos. Não precisa de Akuma no Mi. Contra níveis baixos, a diferença é absoluta se ele decidir agir seriamente."),
    "trafalgar law": dict(nome="Trafalgar Law", titulo="Cirurgião da Morte", classificacao="Supernova", raca="Humano", faccao="Pirata", forca=18000, resistencia=19000, velocidade=22000, akuma="Ope Ope no Mi", haki="Armamento e Observação", estilo="Ope Ope no Mi / espadachim tático", arma="Nodachi (Kikoku)", publico="Capitão dos Piratas Heart e Supernova. Usuário da Ope Ope no Mi, capaz de criar ROOM e manipular espacialmente o que está dentro dela.", combate="Fase Sabaody. Usa ROOM, Shambles/trocas e manipulação/cortes espaciais compatíveis com a fase, nodachi e inteligência tática. Não usar despertar, K-ROOM, Anesthesia, Shock Wille ou Puncture Wille. Veículo principal dos Heart é o submarino Polar Tang. Não faz anúncio teatral do nome Kikoku como técnica."),
}

ALIASES_PROFILE = {
    "zoro": "roronoa zoro", "mihawk": "dracule mihawk", "dragon": "monkey d. dragon",
    "borsalino": "kizaru", "sakazuki": "akainu", "kuzan": "aokiji", "law": "trafalgar law",
    "morgan": "morgan", "axe-hand morgan": "morgan", "zeff perna vermelha": "zeff",
}


def canonical_key(nome: str) -> str:
    chave = " ".join(str(nome).casefold().strip().split())
    return ALIASES_PROFILE.get(chave, chave)


def get_profile(nome: str):
    return NPC_PROFILES.get(canonical_key(nome))


def format_profile_for_narrator(p) -> str | None:
    """Formata perfis fixos e perfis automáticos persistidos."""
    if not p:
        return None
    return (
        f"{p['nome']} — {p['titulo']} / {p['classificacao']}\n"
        f"Raça: {p['raca']} | Facção: {p['faccao']}\n"
        f"ATRIBUTOS DO RP — Força {p['forca']} | Resistência {p['resistencia']} | Velocidade/Agilidade {p['velocidade']}\n"
        f"Akuma no Mi: {p['akuma']} | Haki: {p['haki']}\n"
        f"Estilo: {p['estilo']} | Arma/recurso: {p['arma']}\n"
        f"INFORMAÇÃO PÚBLICA: {p.get('publico', 'Não informada')}\n"
        f"REGRAS DE COMBATE/CÂNONE: {p.get('combate', 'Não inventar capacidades não confirmadas.')}"
    )


def profile_for_narrator(nome: str) -> str | None:
    return format_profile_for_narrator(get_profile(nome))
